### ISSUE TITLE
Following installation guidelines ends with an error

### ISSUE THREAD

**Issue by SBG-bmajic** [helxplatform/radx-synthetic-cdes#5]
Setting up this tool in a python venv by following the provided guidelines results with an error, where ruamel.yaml version 0.2.6 is not found. I'm posting the rest of the error log:

`Collecting pyyaml==5.4.1
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 1.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement ruamel.yaml==0.2.6 (from versions: 0.1, 0.2, 0.3, 0.4, 0.5, 0.5.1, 0.6, 0.6.1, 0.7, 0.7.1, 0.7.2, 0.8, 0.9.1, 0.9.2, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.10, 0.10.1, 0.10.2, 0.10.4, 0.10.5, 0.10.6, 0.10.7, 0.10.8, 0.10.9, 0.10.10, 0.10.11, 0.10.12, 0.10.13, 0.10.14, 0.10.15, 0.10.16, 0.10.17, 0.10.18, 0.10.19, 0.10.20, 0.10.21, 0.10.22, 0.10.23, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.11.5, 0.11.6, 0.11.7, 0.11.8, 0.11.9, 0.11.10, 0.11.11, 0.11.14, 0.11.15, 0.12.0, 0.12.1, 0.12.2, 0.12.3, 0.12.4, 0.12.5, 0.12.6, 0.12.7, 0.12.8, 0.12.9, 0.12.10, 0.12.11, 0.12.12, 0.12.13, 0.12.14, 0.12.15, 0.12.16, 0.12.17, 0.12.18, 0.13.0, 0.13.1, 0.13.2, 0.13.3, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.13.8, 0.13.9, 0.13.10, 0.13.11, 0.13.13, 0.13.14, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.14.5, 0.14.6, 0.14.7, 0.14.8, 0.14.9, 0.14.10, 0.14.11, 0.14.12, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.15.4, 0.15.5, 0.15.6, 0.15.7, 0.15.8, 0.15.9, 0.15.10, 0.15.11, 0.15.12, 0.15.13, 0.15.14, 0.15.15, 0.15.16, 0.15.17, 0.15.18, 0.15.19, 0.15.20, 0.15.21, 0.15.22, 0.15.23, 0.15.24, 0.15.25, 0.15.26, 0.15.27, 0.15.28, 0.15.29, 0.15.30, 0.15.31, 0.15.32, 0.15.33, 0.15.34, 0.15.35, 0.15.37, 0.15.38, 0.15.39, 0.15.40, 0.15.41, 0.15.42, 0.15.43, 0.15.44, 0.15.45, 0.15.46, 0.15.47, 0.15.48, 0.15.49, 0.15.50, 0.15.51, 0.15.52, 0.15.53, 0.15.54, 0.15.55, 0.15.56, 0.15.57, 0.15.58, 0.15.59, 0.15.60, 0.15.61, 0.15.62, 0.15.63, 0.15.64, 0.15.65, 0.15.66, 0.15.67, 0.15.68, 0.15.69, 0.15.70, 0.15.71, 0.15.72, 0.15.73, 0.15.74, 0.15.75, 0.15.76, 0.15.77, 0.15.78, 0.15.79, 0.15.80, 0.15.81, 0.15.82, 0.15.83, 0.15.84, 0.15.85, 0.15.86, 0.15.87, 0.15.88, 0.15.89, 0.15.90, 0.15.91, 0.15.92, 0.15.93, 0.15.94, 0.15.95, 0.15.96, 0.15.97, 0.15.98, 0.15.99, 0.15.100, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.16.7, 0.16.9, 0.16.10, 0.16.11, 0.16.12, 0.16.13, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.17.5, 0.17.6, 0.17.7, 0.17.8, 0.17.9, 0.17.10, 0.17.11, 0.17.12, 0.17.13, 0.17.14, 0.17.15, 0.17.16, 0.17.17, 0.17.18, 0.17.19, 0.17.20, 0.17.21)
ERROR: No matching distribution found for ruamel.yaml==0.2.6
make: *** [install] Error 1`

This is happening on M1 mac, with python version 3.10.4 and pip version 22.2.2.

Installation by using pip3 install -r requirements.txt results with the same error (as expected). I got the code to run by removing this specific package's version constraint (installed the latest version - 0.17.21).

**Comment by asiyahahmad** [comment]
Changing ruamel.yaml version to `0.17.21`
